[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/create-proposal"
  to = "/.netlify/functions/create-proposal"
  status = 200

[[redirects]]
  from = "/api/get-proposal"
  to = "/.netlify/functions/get-proposal"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200

[[redirects]]
  from = "/api/yes-clicked"
  to = "/.netlify/functions/yes-clicked"
  status = 200

[[redirects]]
  from = "/api/delete"
  to = "/.netlify/functions/delete"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "/proposal.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"